version: '3'

services:
  mysql:
    image: mysql/mysql-server:8.0
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql
    ports:
      - 13306:3306
    restart: always

  app:
    build:
      context: ./rb
      dockerfile: Dockerfile
    ports:
      - 9292:9292
    environment:
      - DB_HOST=mysql

volumes:
  mysql:
